certs:
  domain: dphx.eu
  subdomain: cluster.dphx.eu
  email: benjamin.bachmayr@gmail.com
cluster:
  proxmox_node: proxmox-1
base:
  authentik_domain: authentik.cluster.dphx.eu
  argocd_domain: argocd.cluster.dphx.eu
