global:
  domain: argocd.cluster.dphx.eu

configs:
  params:
    server.insecure: true

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    tls: true
    extraTls:
     - hosts:
       - argocd.cluster.dphx.eu
       secretName: argocd-server-tls