authentik:
  secret_key: ${authentik_token}
  bootstrap_password: ${authentik_admin_pw}
  bootstrap_token: ${authentik_admin_token}
  error_reporting:
    enabled: true
  postgresql:
    password: ${postgres_pw}

server:
  ingress:
    enabled: true
    hosts:
      - ${domain}
    ingressClassName: nginx

postgresql:
  enabled: true
  auth:
    password: ${postgres_pw}

redis:
  enabled: true
  